-- Three editorial test scenarios only; no schema changes.
-- Active for testing, not expert-reviewed. The KNOWLEDGE scenario requires medical review.
-- Fixed UUIDs preserve existing records and later edits on rerun.
begin;
insert into public.explore_content (
  content_type, difficulty, estimated_minutes, xp_value, source_type, review_status, active, expert_reviewer, content_id, title, interaction_type, domain, topic, intro, content_body, choices, feedback, teaching_point, source_organization, source_url, medical_review_required, related_content_ids
) values
('PRACTICE_A_SKILL', 'INTRODUCTORY', 2, 10, 'EDITORIAL', 'APPROVED', true, null, '28d7c314-128b-50cf-80bc-200eeb50791d', 'A knife in the shared spread', 'KNOWLEDGE', 'KNOW', 'Recognizing cross-contact', 'A knife has been used on wheat bread and then dipped into a shared spread.', '{"category": "Food preparation", "setting": "A shared kitchen", "prompt": "Which response best addresses the cross-contact risk?", "expert_reviewed": false}'::jsonb, '[{"id": "separate", "label": "Use a separate spread that has not had contact with gluten, with a clean utensil."}, {"id": "crumbs", "label": "Remove the visible crumbs and use the shared spread."}, {"id": "heat", "label": "Heat the shared spread to remove the gluten."}]'::jsonb, '{"by_choice_id": {"separate": "A separate spread and clean utensil help prevent gluten from transferring to your food.", "crumbs": "Removing visible crumbs does not establish that the spread is gluten-free. Choose a separate spread instead.", "heat": "Heat does not eliminate gluten. Use a spread that has not had contact with gluten."}, "preferred_choice": "separate", "safety_issues": {"crumbs": "Gluten may remain in the shared spread.", "heat": "Heating does not make gluten-contaminated food safe."}}'::jsonb, 'Prevent transfer by checking both the food and the utensils used with it.', 'Beyond Celiac', 'https://www.beyondceliac.org/gluten-free-diet/cross-contact/', true, ARRAY['87aca241-c8d5-4c45-b7d6-b786b08f7d01'::uuid]::uuid[]),
('PRACTICE_A_SKILL', 'INTRODUCTORY', 2, 10, 'EDITORIAL', 'APPROVED', true, null, '91453ad5-311b-585f-8647-cc1694d781b0', 'Choose your way to ask', 'CHOICE', 'SPEAK', 'Requesting support', 'You want to ask the host about the food plan. You can choose how to start the conversation.', '{"category": "Communication", "setting": "Before a gathering", "prompt": "Which approach would fit you today?", "expert_reviewed": false}'::jsonb, '[{"id": "message", "label": "Send a message ahead of time."}, {"id": "talk", "label": "Have a quiet conversation with the host."}, {"id": "support", "label": "Ask a trusted person to help start the conversation."}]'::jsonb, '{"by_choice_id": {"message": "A message gives you time to choose your words. You could start by asking when the host has time to talk about the food plan.", "talk": "A quiet conversation may suit you. You can choose a moment when the host has time to listen.", "support": "Asking someone to help is a reasonable option. You can decide together what you want to ask and how much you want to say."}, "preferred_choice": null, "safety_issues": {}}'::jsonb, 'You can choose a communication approach that fits your needs.', 'Plan My C-Day — editorial test scenario', null, false, ARRAY[]::uuid[]),
('PRACTICE_A_SKILL', 'INTRODUCTORY', 2, 10, 'EDITORIAL', 'APPROVED', true, null, 'b69af127-5994-5cc0-bd2c-053edff234b8', 'What would help today?', 'REFLECTION', 'TRUST', 'Recognizing support needs', 'Pause and notice what kind of support you would welcome today. There is no right answer.', '{"category": "Self-reflection", "setting": "A moment to check in", "prompt": "Which feels closest to what you need?", "expert_reviewed": false}'::jsonb, '[{"id": "space", "label": "A little space before I make a plan."}, {"id": "listen", "label": "Someone who will listen."}, {"id": "step", "label": "One small next step."}, {"id": "unsure", "label": "I am not sure yet."}]'::jsonb, '{"by_choice_id": {"space": "You chose a little space. You can pause and return to planning when you feel ready; you do not have to solve everything in this moment.", "listen": "You chose someone who will listen. You might tell a trusted person, “Could you listen for a minute before we think about solutions?”", "step": "You chose one small step. Consider picking a single thing you would like support with, rather than working out the whole day.", "unsure": "Not knowing yet is a valid response. You can notice how you feel now and check in again later."}, "preferred_choice": null, "safety_issues": {}}'::jsonb, 'Your support needs can change from day to day.', 'Plan My C-Day — editorial test scenario', null, false, ARRAY[]::uuid[])
on conflict (content_id) do nothing;
commit;

select content_id, title, interaction_type, active from public.explore_content
where content_id in ('28d7c314-128b-50cf-80bc-200eeb50791d'::uuid,'91453ad5-311b-585f-8647-cc1694d781b0'::uuid,'b69af127-5994-5cc0-bd2c-053edff234b8'::uuid)
order by interaction_type;
