import {useState} from 'react';
import {Text,View,Pressable,StyleSheet,TextInput} from 'react-native';
import {ExploreActionButton as Button} from './explore-action-button';
import {builderQuestions,contextTags,suggestActions,matchingTemplates,type BuilderAnswers,type PlanTemplate} from '@/lib/custom-model';
import {saveBuilder,getTemplates,useTemplate,saveTemplate} from '@/lib/custom-data';
import type {CDayEvent,CDayAction,LibraryAction} from '@/lib/c-day-model';
export function CustomBuilder({event,items,actions,busy,onAdd,onRemove,onRefresh,onAll,onPlan}:{event:CDayEvent;items:LibraryAction[];actions:CDayAction[];busy:boolean;onAdd:(a:LibraryAction)=>void;onRemove:(a:CDayAction)=>void;onRefresh:()=>Promise<void>;onAll:()=>void;onPlan:()=>void}){
 const [answers,setAnswers]=useState<BuilderAnswers>(event.custom_context?.answers??{}),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[templates,setTemplates]=useState<PlanTemplate[]>([]),[message,setMessage]=useState('');
 const disabled=busy||saving;
 async function build(){setSaving(true);setError('');try{await saveBuilder(event.id,answers);await onRefresh();setReady(true);try{setTemplates(matchingTemplates(await getTemplates(event.user_id),event.title,contextTags(answers)));}catch{setMessage('Saved plans couldn’t load. You can still choose actions.');}}catch{setError('Your Builder couldn’t save. Please try again.');}finally{setSaving(false);}}
 async function reuse(t:PlanTemplate){setSaving(true);setError('');try{const result=await useTemplate(event.id,t.id);await onRefresh();setTemplates([]);setMessage(result.unavailable?'Some saved actions are no longer available. Choose other actions below.':'Selections added. Review and schedule each action for this C-Day.');}catch{setError('The saved plan couldn’t be used. Your draft is safe; retry or choose actions.');await onRefresh();}finally{setSaving(false);}}
 return <View style={s.wrap}>
 {!ready?<><Text style={s.heading}>Build my C-Day</Text><Text style={s.body}>Choose what fits. You can skip any question.</Text>{builderQuestions.map(q=><View key={q.id} style={s.card}><Text style={s.heading}>{q.question}</Text><View style={s.choices}>{q.choices.map(([label,value])=>{const selected=(answers[q.id]??[]).includes(value);return <Pressable key={value} accessibilityRole="checkbox" accessibilityState={{checked:selected,disabled}} disabled={disabled} onPress={()=>setAnswers(a=>({...a,[q.id]:selected?(a[q.id]??[]).filter(x=>x!==value):q.multiple?[...(a[q.id]??[]),value]:[value]}))} style={[s.chip,selected&&s.selected]}><Text style={s.body}>{selected?'✓ ':''}{label}</Text></Pressable>})}</View></View>)}<Button label={saving?'Saving…':'BUILD MY C-DAY'} onPress={()=>void build()} disabled={disabled}/></>:<>
 <Text style={s.heading}>Here’s a starting plan for your C-Day.</Text><Text style={s.body}>Based on what you told us, here are some things that might help. Pick the 2–6 that feel useful to you.</Text>
 {!actions.length&&templates.length>0&&<View style={s.card}><Text style={s.heading}>You planned something like this before. Start with that plan?</Text>{templates.map(t=><View key={t.id} style={s.wrap}><Text style={s.body}>{t.title}</Text><Button label="USE MY LAST PLAN" onPress={()=>void reuse(t)} disabled={disabled}/></View>)}<Button variant="navigation" label="START FRESH" onPress={()=>setTemplates([])} disabled={disabled}/></View>}
 <Button label="SEE ALL ACTIONS" onPress={onAll} disabled={disabled}/><Text style={s.body}>{actions.length} of 6 selected</Text>
 {suggestActions(items,answers).map(item=>{const selected=actions.find(a=>a.action_library_id===item.id);return <View style={s.card} key={item.id}><Text style={s.caption}>{item.category}</Text><Text style={s.body}>{item.action_text}</Text><Button variant="choice" label={selected?'✓ Remove from my plan':'Add to my plan'} onPress={()=>selected?onRemove(selected):onAdd(item)} disabled={disabled||(!selected&&actions.length>=6)}/></View>})}
 <Button label="Review and schedule my actions" onPress={onPlan} disabled={disabled}/><Button variant="navigation" label="Edit Builder answers" onPress={()=>setReady(false)} disabled={disabled}/>
 </>}{!!message&&<Text style={s.body}>{message}</Text>}{!!error&&<Text accessibilityRole="alert" style={s.body}>{error}</Text>}
 </View>;
}
export function CustomSnapshot({event,actions}:{event:CDayEvent;actions:CDayAction[]}){
 const support=builderQuestions.find(q=>q.id==='support')!;
 const labels=support.choices.filter(c=>(event.custom_context?.answers?.support??[]).includes(c[1])).map(c=>c[0]);
 return <View style={s.card}><Text style={s.heading}>{event.title}</Text><Text style={s.body}>{new Date(event.event_start_at).toLocaleString(undefined,{timeZone:event.event_timezone})}</Text><Text style={s.heading}>MY GAME PLAN</Text>{actions.filter(a=>a.completion_status!=='not_needed').map(a=><Text key={a.id} style={s.body}>✓ {a.action_text_snapshot}</Text>)}{labels.length>0&&<><Text style={s.heading}>MY SUPPORT</Text><Text style={s.body}>{labels.join(' · ')}</Text></>}<Text style={s.heading}>I’M FEELING</Text><Text style={s.body}>{'★'.repeat(event.plan_rating??0)}{'☆'.repeat(5-(event.plan_rating??0))} about my plan</Text><Text style={s.body}>You made the plan. Now go have your C-Day.</Text></View>;
}
export function SaveCustomTemplate({event}:{event:CDayEvent}){
 const [title,setTitle]=useState(event.title),[saving,setSaving]=useState(false),[hidden,setHidden]=useState(false),[message,setMessage]=useState('');
 if(hidden)return message?<Text style={s.body}>{message}</Text>:null;
 return <View style={s.card}><Text style={s.heading}>Would you want to use this plan again?</Text><TextInput accessibilityLabel="Saved-plan title" value={title} onChangeText={setTitle} maxLength={200} editable={!saving} style={[s.body,s.chip]}/><Button label={saving?'Saving…':'SAVE AS MY C-DAY'} disabled={saving||!title.trim()} onPress={()=>{setSaving(true);void saveTemplate(event.id,title).then(()=>{setMessage('Saved privately. New C-Days will need new schedules and difficulty ratings.');setHidden(true)}).catch(()=>setMessage('Couldn’t save your template. Please try again.')).finally(()=>setSaving(false))}}/><Button variant="navigation" label="NOT NOW" disabled={saving} onPress={()=>{setMessage('');setHidden(true)}}/>{!!message&&<Text style={s.body}>{message}</Text>}</View>;
}
const s=StyleSheet.create({wrap:{gap:16},card:{padding:18,gap:14,borderRadius:20,backgroundColor:'#EDF3E6',borderWidth:1,borderColor:'#C5DDB5'},heading:{fontSize:20,lineHeight:28,fontWeight:'600',color:'#34472F'},body:{fontSize:16,lineHeight:24,color:'#62556E'},caption:{fontSize:14,lineHeight:21,color:'#62556E'},choices:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{padding:14,minHeight:48,borderWidth:1,borderColor:'#C5DDB5',borderRadius:14,backgroundColor:'#FFFDF8'},selected:{backgroundColor:'#D7E7C7',borderColor:'#496B36',borderWidth:2}});
